name: integration
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/enterprise-search@master
        with:
          stack-version: 7.7.0

      - name: Enterprise Search is reachable
        run: |
          curl --verbose --show-error http://localhost:8080/swiftype-app-version
